version: '3'
services:
  binddb:
    image: mysql:8
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  mountdb:
    image: mysql:8
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mountdb:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
volumes:
  mountdb:
    driver: "local"